### ISSUE TITLE
MySQL 5.7.20 连接报错（请增加默认时区/设置时区）

### ISSUE THREAD

**Issue by ghost** [yhl452493373/CodeGenerator#1]
错误详情：
java.sql.SQLException: The server time zone value 'ÖÐ¹ú±ê×¼Ê±¼ä' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.

解决办法：
在：com.github.yhl452493373.generator.CodeGeneratorConfig中的159行修改为：
this.dataSourceUrl = "jdbc:mysql://" + host + ":" + port + "/" + database + "?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8";
增加了&serverTimezone=GMT%2B8，东8区。

**Comment by yhl452493373** [comment]
可以先用自定义数据库地址的方式解决：
属性名：dataSourceUrl
这个属性需要完整的jdbcUrl地址。
时区我下次加上去。

**Comment by yhl452493373** [comment]
> 可以先用自定义数据库地址的方式解决：
> 属性名：dataSourceUrl
> 这个属性需要完整的jdbcUrl地址。
> 时区我下次加上去。

因为我这边用的MySQL是5.7.17还是多少来着，没出现这个问题，可能mysql升级版本后有点差别
